login/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    name = StringField('Title',validators=[DataRequired()])
    author= TextAreaField('Content',validators=[DataRequired()])
    submit = SubmitField('Post')

login/main/routes.py
from flask import render_template, request, Blueprint,current_app, jsonify
from login.models import Post
import atexit
from apscheduler.schedulers.background import BackgroundScheduler
import requests
#from login import STOCK_VALUE

main = Blueprint('main',__name__)

def get_call():
    r = requests.get("http://localhost:5001/stocks?no_stocks=100").json()
    #print(r['data'][0])
    return r

@main.route('/')
@main.route('/home')
def home():
    
    r= get_call()
    # scheduler = BackgroundScheduler()
    # scheduler.add_job(func=get_call, trigger="interval", seconds=3)
    # scheduler.start()
    # print(r)
    # # Shut down the scheduler when exiting the app
    # atexit.register(lambda: scheduler.shutdown())
    
    # current_app.logger.info("Processing home request")
    #print(STOCK_VALUE)
    posts = Post.query.all() 
    return render_template('home.html',posts=posts,data=r)

@main.route('/about')
def about():
    return render_template('about.html',title='About')

@main.route('/refresh_data')
def refresh_data():
    
    r= get_call()
    # scheduler = BackgroundScheduler()
    # scheduler.add_job(func=get_call, trigger="interval", seconds=3)
    # scheduler.start()
    # print(r)
    # # Shut down the scheduler when exiting the app
    # atexit.register(lambda: scheduler.shutdown())
    
    # current_app.logger.info("Processing home request")
    #print(STOCK_VALUE)
    return jsonify(r)

login/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from login import db
from login.models import Post
from login.posts.forms import PostForm

posts = Blueprint('posts',__name__)

@posts.route('/post/new',methods=['GET','POST'])
@login_required
def new_post():
    form  = PostForm()
    if form.validate_on_submit():
        post = Post(name=form.name.data,author=form.author.data,user_id=current_user.id)
        db.session.add(post)
        db.session.commit()
        flash('Your Post has been created','success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html',title='New Post',form=form,legend = 'New Post')

@posts.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html',title=post.name,post=post)

    
@posts.route('/post/<int:post_id>/update',methods=['GET','POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.user_id != current_user.id:
        abort(403)
    form =PostForm()
    if form.validate_on_submit():
        post.name = form.name.data
        post.author = form.author.data
        db.session.commit()
        flash("Your post has been updated",'success')
        return redirect(url_for('posts.post',post_id=post.id))
    elif request.method == 'GET':
        form.name.data= post.name
        form.author.data= post.author
    return render_template('create_post.html',title='Update Post',form=form,legend = 'Update Post')

@posts.route('/post/<int:post_id>/delete',methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.user_id != current_user.id:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash("Your post has been deleted",'success')
    return redirect(url_for('main.home'))

login/stocks/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint, jsonify)
from flask_login import current_user, login_required
from login import db, cache, q
from login.models import BuyStocks, Stock, BankAccount,SellStocks, UserStocks
from login.stocks.forms import BuyStocksForm, SellStocksForm, TransferMoneyForm, PlanScheduleForm, StockForm
import schedule
import time
import atexit
from apscheduler.schedulers.background import BackgroundScheduler
#from flask.ext.restless import APIManager


stocks = Blueprint('stocks',__name__)

@stocks.route('/buystocks', methods=['GET','POST'])
#@cache.cached(timeout=50)
@login_required
def buy_stocks():
    form = BuyStocksForm()
    if form.validate_on_submit():
        cache.clear()

        stock = Stock.query.filter_by(ticker_symbol=form.ticker_symbol.data).first()
        buy_stock = BuyStocks(ticker_symbol=form.ticker_symbol.data, user_id=current_user.id,buy_price=stock.price,no_of_stocks=form.no_of_stocks.data)
        db.session.add(buy_stock)
        user_stock_query = UserStocks.query.filter_by(ticker_symbol=form.ticker_symbol.data,user_id=current_user.id).first()
        if user_stock_query is None:
            user_stock = UserStocks(ticker_symbol=form.ticker_symbol.data,user_id=current_user.id,no_of_stocks=form.no_of_stocks.data,company_name=stock.company_name)
            db.session.add(user_stock)
        else:
            new_no_of_stocks = (user_stock_query.no_of_stocks + form.no_of_stocks.data)
            UserStocks.query.filter_by(ticker_symbol=form.ticker_symbol.data,user_id=current_user.id).update({'no_of_stocks':new_no_of_stocks})
        bank_account1 = BankAccount.query.filter_by(bank_account_no=form.bank_account_no.data.bank_account_no,user_id=current_user.id).first()
        new_amount= bank_account1.amount-(stock.price * form.no_of_stocks.data)
        BankAccount.query.filter_by(user_id=current_user.id, bank_account_no=form.bank_account_no.data.bank_account_no).update({'amount':new_amount})
        db.session.commit()
        
        flash('You have successfully bought the stock','success')
        
        return redirect(url_for('main.home'))
    return render_template('buystocks.html',title='Buy Stocks',form = form, legend = 'Buy Stocks')

@stocks.route('/sellstocks',methods=['GET','POST'])
#@cache.cached(timeout=50)
@login_required
def sell_stocks():
    form = SellStocksForm()
    if form.validate_on_submit():
        cache.clear()
        stock = Stock.query.filter_by(ticker_symbol=form.ticker_symbol.data).first()
        # buy_stock_price= BuyStocks.query.filter_by(ticker_symbol=form.ticker_symbol.data,user_id=current_user.id).first()
        # sell_stock = SellStocks(ticker_symbol=form.ticker_symbol.data,user_id=current_user.id,buy_price=buy_stock_price.buy_price,selling_price=stock.price,no_of_stocks=form.no_of_stocks.data)
        sell_stock = SellStocks(ticker_symbol=form.ticker_symbol.data,user_id=current_user.id,selling_price=stock.price,no_of_stocks=form.no_of_stocks.data)
        db.session.add(sell_stock)
        bank_account1 = BankAccount.query.filter_by(bank_account_no=form.bank_account_no.data.bank_account_no,user_id=current_user.id).first()
        new_amount= bank_account1.amount+(stock.price * form.no_of_stocks.data)
        BankAccount.query.filter_by(user_id=current_user.id, bank_account_no=form.bank_account_no.data.bank_account_no).update({'amount':new_amount})
        BuyStocks.query.filter_by(user_id=current_user.id,ticker_symbol=form.ticker_symbol.data).delete()
        user_stock_query = UserStocks.query.filter_by(ticker_symbol=form.ticker_symbol.data,user_id=current_user.id).first()
        new_no_of_stocks = (user_stock_query.no_of_stocks - form.no_of_stocks.data)
        UserStocks.query.filter_by(ticker_symbol=form.ticker_symbol.data,user_id=current_user.id).update({'no_of_stocks':new_no_of_stocks})
        db.session.commit()
        flash('You have successfully sold the stock','success')
        return redirect(url_for('main.home'))
    return render_template('sellstocks.html',title='Sell Stocks',form = form, legend = 'Sell Stocks')

@stocks.route('/mystocks')
@cache.cached(timeout=100)
@login_required
def mystocks():
    var = cache.get('mystocks')
    #print(var)
    cache.clear()    
    if var is None:
        print("Cache Miss")
        # cache.set('mystocks',var,timeout=100)
    else:
        print("Cache Hit")
    
    stocks = UserStocks.query.filter_by(user_id=current_user.id)
    # stocks1 = stocks.query.filter_by()
    return render_template('mystocks.html',stocks=stocks, legend = 'My Stocks')

@stocks.route('/transfermoney',methods=['GET','POST'])
#@cache.cached(timeout=50)
@login_required
def transfer_money():
    form = TransferMoneyForm()
    print("Form rendered")
    if form.validate_on_submit():
        
        bank_account1 = BankAccount.query.filter_by(bank_account_no=form.bank_account_no1.data.bank_account_no,user_id=current_user.id).first()
        bank_account2 = BankAccount.query.filter_by(bank_account_no=form.bank_account_no2.data.bank_account_no,user_id=current_user.id).first()
        new_amount_for1= (bank_account1.amount - form.amount_to_transfer.data)
        new_amount_for2= (bank_account2.amount + form.amount_to_transfer.data)
        BankAccount.query.filter_by(user_id=current_user.id, bank_account_no=bank_account1.bank_account_no).update({'amount':new_amount_for1})  
        BankAccount.query.filter_by(user_id=current_user.id, bank_account_no=bank_account2.bank_account_no).update({'amount':new_amount_for2})
        db.session.commit()
        flash('You have successfully transferred the money!','success')
        return redirect(url_for('main.home'))
    return render_template('transfermoney.html',title='Transfer Money',form = form, legend = 'Transfer Money')

def call_pending():
        schedule.run_pending()
        time.sleep(1)
    

@stocks.route('/planschedule',methods=['GET','POST'])
#@cache.cached(timeout=50)
@login_required
def plan_schedule():
    form = PlanScheduleForm()
    
    def buy():
        print("Scheduled stock has been bought!")
        ##Call the logic for buying scheduled stock
        # stock = Stock.query.filter_by(ticker_symbol=form.ticker_symbol.data).first()
        # buy_stock = BuyStocks(ticker_symbol=form.ticker_symbol.data,user_id=current_user.id,buy_price=stock.price,no_of_stocks=form.no_of_stocks.data)
        # db.session.add(buy_stock)
        # user_stock_query = UserStocks.query.filter_by(ticker_symbol=form.ticker_symbol.data,user_id=current_user.id).first()
        # if user_stock_query is None:
        #     user_stock = UserStocks(ticker_symbol=form.ticker_symbol.data,user_id=current_user.id,no_of_stocks=form.no_of_stocks.data)
        #     db.session.add(user_stock)
        # else:
        #     new_no_of_stocks = (user_stock_query.no_of_stocks + form.no_of_stocks.data)
        #     UserStocks.query.filter_by(ticker_symbol=form.ticker_symbol.data,user_id=current_user.id).update({'no_of_stocks':new_no_of_stocks})
        # bank_account1 = BankAccount.query.filter_by(bank_account_no=form.bank_account_no.data.bank_account_no,user_id=current_user.id).first()
        # new_amount= bank_account1.amount-(stock.price * form.no_of_stocks.data)
        # BankAccount.query.filter_by(user_id=current_user.id, bank_account_no=form.bank_account_no.data.bank_account_no).update({'amount':new_amount})
        # db.session.commit()

        
    if form.validate_on_submit():
        #schedule.every().friday.at("00:46").do(buy) 
        schedule.every(2).minutes.do(buy)    
        
        scheduler = BackgroundScheduler()
        scheduler.add_job(func=call_pending, trigger="interval", seconds=3)
        scheduler.start()
        #print("scheduler started")
        # Shut down the scheduler when exiting the app
        atexit.register(lambda: scheduler.shutdown())


        flash('You have successfully planned the buy schedule!','success')
        return redirect(url_for('main.home'))
        
   
    
    return render_template('planschedule.html',title='Plan Schedule',form = form, legend = 'Plan Schedule')

 
# @login_required
# @stocks.route('/buy-stocks')
# def buy_stocks1():
#     #user = current_user
#     #db_object
#     list_of_stocks = []
#     return jsonify({"list_of_stocks":list_of_stocks})

@login_required
@stocks.route('/get_stock_tickers')
@cache.cached(timeout=50)
def get_stock_tickers():
    stocks = Stock.query.all()
    list_of_stocks=list()
    for stock in stocks:
        list_of_stocks.append(stock.ticker_symbol)

    return jsonify({"list_of_stock_tickers":list_of_stocks})

@login_required
@stocks.route('/get_user_bank_accounts')
@cache.cached(timeout=50)
def get_user_bank_account():
    bank_accounts = BankAccount.query.filter_by(user_id=current_user.id).all()
    list_of_accounts=list()
    for account in bank_accounts:
        list_of_accounts.append(account.bank_account_no)

    return jsonify({"list_of_stocks":list_of_accounts})


@login_required
@stocks.route('/get_stocks')
@cache.cached(timeout=50)
def get_stocks():
    stocks = Stock.query.all()
    list_of_stocks = list()
    for stock in stocks:
        list_of_stocks.append(stock)

    return jsonify({"":list_of_stocks})


login/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from login import db, bcrypt
from login.models import User, Post, BankAccount
from login.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from login.users.utils import save_picture, send_reset_email

users = Blueprint('users',__name__)

@users.route('/register',methods=['GET','POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form=RegistrationForm()
    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data,address=form.address.data,email=form.email.data,password=hashed_pw)
        db.session.add(user)
        
        flash('Your account has been created! You can now log in ' , 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html',title='Register', form=form) 

@users.route('/login',methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form=LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password,form.password.data):    
            login_user(user,remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash(f'Email id or password incorrect!','danger')
    return render_template('login.html',title='Login', form=form)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route('/account',methods=['GET','POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file=save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.address = form.address.data
        db.session.commit()
        flash('Your account info has been updated','success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.address.data = current_user.address
    bank_account = BankAccount.query.filter_by(user_id=current_user.id).first()
    image_file = url_for('static',filename='profile_pics/'+ current_user.image_file)
    return render_template('account.html',title='Account',image_file=image_file, form = form,bank_account=bank_account)

@users.route('/reset_password',methods=['GET','POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password','info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html',title ='Reset Password', form =form)

@users.route('/reset_password/<token>',methods=['GET','POST'])
def reset_token(token):
    
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Expired token','warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password=hashed_pw
        db.session.commit()
        flash('Your password has been updated! You can now log in ' , 'success')
        return redirect(url_for('users.login'))

    return render_template('reset_token.html',title ='Reset Password', form =form)

login/templates/about.html
{% extends "layout.html"%}
{% block content%}
    <h1>About Page</h1>
{% endblock content%}

login/templates/account.html
{% extends "layout.html"%}
{% block content%}
    <div class="content-section">
        <div class="media">
            <img class="rounded-circle account-img" src="{{image_file}}">
            <div class="media-body">
            <h2 class="account-heading">{{ current_user.username }}</h2>
            <p class="text-secondary">Email:{{ current_user.email }}</p>
            <p class="text-secondary">Address:{{ current_user.address }}</p>
            <p class="text-secondary">Bank Account No.:{{bank_account.bank_account_no}}</p>
            </div>
        </div>
    <!-- FORM HERE -->
    
            <form method="POST" action="" enctype="multipart/form-data">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Account Info</legend>
                    <div class="form-group">
                        {{ form.username.label(class="form-control-label") }}
                        {% if form.username.errors %}
                            {{ form.username(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.username.errors %}
                                    <span> {{ error}}</span>
                                {% endfor %}
                            </div>    
                        {% else %}
                            {{ form.username(class="form-control form-control-lg") }}
                        {% endif %}
                            
                    </div>
                    <div class="form-group">
                            {{ form.address.label(class="form-control-label") }}
                            {% if form.address.errors %}
                            {{ form.address(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.address.errors %}
                                    <span> {{ error}}</span>
                                {% endfor %}
                            </div>    
                        {% else %}
                            {{ form.address(class="form-control form-control-lg") }}    
                        {% endif %}
                            
                        </div>
                    <div class="form-group">
                            {{ form.email.label(class="form-control-label") }}
                            {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span> {{ error}}</span>
                                {% endfor %}
                            </div>    
                        {% else %}
                            {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}
                            
                            
                    </div>  
                    <div class="form-group">
                            {{ form.picture.label() }}
                            {{ form.picture(class = "form-control-file") }}
                            {% if form.picture.errors%}
                                {% for error in form.picture.errors %}
                                <span class = "text-danger"> {{ error}}</span><br>
                                {% endfor %}
                            {% endif%}
                    </div>                                        
                </fieldset>
                <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info")}}
                </div>
            </form>
        </div>
    
{% endblock content%}

login/templates/layout.html
<html>
    <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        
            <!-- Bootstrap CSS -->
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
            <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

            
        {% if title %}
            <title>Stock Website - {{ title }} </title>
        {% else %} 
            <title>Stock Website</title>
        {% endif%}   
    </head>
    <body >
            <header class="site-header">
                    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
                      <div class="container py-3">
                        <a class="navbar-brand mr-4" href="/">Spiders</a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                          <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarToggle">
                          <div class="navbar-nav mr-auto">
                            <a class="nav-item nav-link" href="{{url_for('main.home')}}">Home</a>
                            <a class="nav-item nav-link" href="{{url_for('main.about')}}">About</a>
                          </div>
                          <!-- Navbar Right Side -->
                          <div class="navbar-nav">
                            {% if current_user.is_authenticated %}
                              <!-- <a class="nav-item nav-link" href="{{url_for('posts.new_post')}}">New Post</a> -->
                              <a class="nav-item nav-link" href="{{url_for('stocks.mystocks')}}">My Stocks</a>
                              <a class="nav-item nav-link" href="{{url_for('users.account')}}">Account</a>
                              <a class="nav-item nav-link" href="{{url_for('users.logout')}}">Logout</a>
                            {% else %}
                              <a class="nav-item nav-link" href="{{url_for('users.login')}}">Login</a>
                              <a class="nav-item nav-link" href="{{url_for('users.register')}}">Register</a>
                            {% endif %}  
                          </div>
                        </div>
                      </div>
                    </nav>
            </header>

            <div class="bg-success py-3 mb-4 mt-4">
                <div class="container">
                  <!-- <div class="row h-100 align-items-center"> -->
                    <!-- <div class="col-lg-12"> -->
                      <h2 class="display-4 text-white mt-3">Stock Exchange</h2>
                    <!-- </div> -->
                  <!-- </div> -->
                </div>
              </div>
        <main role="main" class="container">
                <div class="row">
                    <div class="col-md-8">
                    {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages%}
                        {% for category,message in messages %}
                            <div class="alert alert-{{category}}">
                                {{message}}
                            </div>
                        {% endfor %}
                    {% endif %}
                    {% endwith %}
                    {% block content %}{% endblock %}
                    </div>
                    <div class="col-md-4 ">
                    <div class="content-section bg-dark">
                        <h3 class="text-white">Task Bar </h3>
                        <p class='text-white'>Actions:
                        <ul class="list-group">
                            <li class="list-group-item list-group-item-light"><a class="nav-item nav-link " href="{{url_for('bankaccounts.addbankaccount')}}">Add Bank Account</a></li>
                            <li class="list-group-item list-group-item-light"><a class="nav-item nav-link" href="{{url_for('stocks.buy_stocks')}}">Buy Stocks</a></li>
                            <li class="list-group-item list-group-item-light"><a class="nav-item nav-link" href="{{url_for('stocks.sell_stocks')}}">Sell Stocks</a></li>
                            <li class="list-group-item list-group-item-light"><a class="nav-item nav-link" href="{{url_for('stocks.transfer_money')}}">Transfer Money Between bank accounts</a></li>
                            <li class="list-group-item list-group-item-light"><a class="nav-item nav-link" href="{{url_for('stocks.plan_schedule')}}">Plan a buy schedule</a></li>
                        </ul>
                        </p>
                    </div>
                    </div>
                </div>
        </main>
        <!-- Footer -->
  <div class="py-4">

  </div>
  <footer class="py-4 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white"> Website for stockmarket enthusiasts</p>
        <p class="m-0 text-center text-white"> spiderswpl@gmail.com</p>
      </div>
      <!-- /.container -->
    </footer>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>

</html>

login/templates/post.html

{% extends "layout.html"%}
{% block content%}
    <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                <a class="mr-2" href="#">{{ post.author }}</a> 
                {% if post.user_id == current_user.id %}
                    <div>
                        <a class = "btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post',post_id = post.id) }}">Update</a>
                        <button type = "button" class = "btn btn-danger btn-sm m-1 mb-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
                    </div>
                {% endif %}    
                <!-- <small class="text-muted">{{ post.date_posted }}</small> -->
                </div>
                
                <h2 class= "article-title">{{ post.name }}</h2>
                <!-- <p class="article-content">{{ post.content }}</p> -->
            </div>
    </article>
    <!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <form action="{{url_for('posts.delete_post',post_id=post.id)}}" method="POST">
                    <input class = "btn btn-danger" type="submit" value="Delete">
              </form>
            </div>
          </div>
        </div>
      </div>
{% endblock content%}

login/templates/reset_request.html
{% extends "layout.html"%}
{% block content%}
    <div class="content-section">
        <form method="POST", action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                
                
                <div class="form-group">
                        {{ form.email.label(class="form-control-label") }}
                        {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span> {{ error}}</span>
                            {% endfor %}
                        </div>    
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                        
                        
                </div>  
                                    
                
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-success")}}
            </div>

            
        </form>
    </div>
    
{% endblock content%}